Use the Jackson BOM to solve Jackson dependency errors (#523)
Using Azure OpenAI, on some Jackson mappings I'm getting the following
error:
```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonTypeInfo$Value
```
This is because not all our Jackson dependencies are using the same
version. The intent of this commit is to fix this, by using the Jackson
BOM.