Update google-vertex-ai.md (#2493)
Removed multimodalembedding from the list of supported embedding models
because Vertex AI's multimodalembedding is not supported in this method
and it results in the error:
com.google.api.gax.rpc.InvalidArgumentException:
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: computeTokens is
infeasible

Preview of modification in the doc after removal of the mention of
multimodal embeddings:
![Unit Test - Preview of modification in the doc after removal of the
mention of multimodal
embeddings](https://github.com/user-attachments/assets/2600443b-dddc-4068-af85-95fc281592bd)


## Issue
<!-- Please specify the ID of the issue this PR is addressing. For
example: "Closes #1234" or "Fixes #1234" -->
Closes #2465 

## Change
<!-- Please describe the changes you made. -->
Only documentation change. Removed "multimodalembedding" from the list
of supported embedding models. No code change. This doc change is needed
because Vertex AI's multimodalembedding is not supported in this method
and it results in the error:
"com.google.api.gax.rpc.InvalidArgumentException:
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: computeTokens is
infeasible"

## General checklist
<!-- Please double-check the following points and mark them like this:
[X] -->
- [X] There are no breaking changes
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the
module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the
[core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core)
and
[main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j)
modules, and they are all green
<!-- Before adding documentation and example(s) (below), please wait
until the PR is reviewed and approved. -->
- [ ] I have added/updated the
[documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples
repo](https://github.com/langchain4j/langchain4j-examples) (only for
"big" features)
- [ ] I have added/updated [Spring Boot
starter(s)](https://github.com/langchain4j/langchain4j-spring) (if
applicable)

Co-authored-by: Guillaume Laforge <glaforge@gmail.com>
Co-authored-by: Dmytro Liubarskyi <ljubarskij@gmail.com>